### ISSUE TITLE
Where is eval.py？

### ISSUE THREAD

**Issue by SilenceWinter** [nlpcl-lab/bert-event-extraction#1]
Thanks for your sharing！ But where is eval.py？

**Comment by bowbowbow** [comment]
@SilenceWinter 

I just added it. Can you check the latest commit? 

As shown in README, the argument classification performance is low. 😢 
Can you help us improve it?

**Comment by SilenceWinter** [comment]
Firstly I am a newer in event extraction aspect.  So this is just my simple idea.  ^-^

 I read your code，the model seems like  BERT + fc1+ fc2 . I think the model maybe too simple to catch the feature  ,although BERT is strong in other tasks. Actually this dataset is too small.

I also read the paper of JMEE model and I agree that GNN could really catch more richer feature in this task. But I have not read the code of JMEE and I plan to read it.

And I found another little bug (maybe I misread) in data_load.py  line 99-100 .As below:
        assert len(tokens_x) == len(entities_x) == len(triggers_y) == len(arguments_y), \
            'len(tokens_x)={}, len(entities_x)={}, len(triggers_y)={}, len(triggers_y)={}'.format(len(tokens_x), len(entities_x), len(arguments_y), len(arguments_y))

^-^

**Comment by bowbowbow** [comment]
@SilenceWinter 

I had a hard time thinking alone, but your suggestion gave me a big boost :) I'll add GNN and compare the performance.

I agree that the model is too simple while the number of data is small. It has been reported that there is little performance improvement when using other layers with the BERT model in similar squence tagging task such as NER ([Kyubyong/bert_ner](https://github.com/Kyubyong/bert_ner), [sberbank-ai/ner-bert](https://github.com/sberbank-ai/ner-bert)). I also didn't use any additional layers when using the BERT model.

The bug you told me has been resolved in the latest version. Thank you!
