### ISSUE TITLE
关于结果的疑问

### ISSUE THREAD

**Issue by Wangpeiyi9979** [nlpcl-lab/bert-event-extraction#10]
不知道您读过这篇文章没有：《Exploring Pre-trained Language Models for Event Extraction and Generation
Sen》

他直接吧trigger的识别准确率推到了80%
![image](https://user-images.githubusercontent.com/42565075/95077200-ac501780-0745-11eb-9c57-f1328d3272f4.png)

**Comment by kimetsu-hash** [comment]
我也看了这篇文章，但是20年事件检测领域的文章都没引用这篇的实验数据做对比

**Comment by RZFan525** [comment]
> 

想问一下您，这篇文章的结果可以复现吗？

**Comment by Wangpeiyi9979** [comment]
> 
您好，当初只是很简单跑了一下实验，但是感觉和论文里差的有点多，就没有再扣细节了，后来也没做这个方向了，也许仔细调参后能够复现吧，我也不清楚。

**Comment by RZFan525** [comment]
> > 
> 
> 您好，当初只是很简单跑了一下实验，但是感觉和论文里差的有点多，就没有再扣细节了，后来也没做这个方向了，也许仔细调参后能够复现吧，我也不清楚。

好吧  谢谢您~
